name: Spark
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: Spark Olllama
    provider: ollama
    model: codegemma:7b
    apiBase: http://spark:11434
    capabilities:
      - tool_use

# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
mcpServers:
  - uses: anthropic/memory-mcp
